# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('disruption_title', models.CharField(max_length=200)),
                ('disruption_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=10)),
                ('line_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='disruption',
            name='metro_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disruptions.MetroLine'),
        ),
    ]
