# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disruptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disruption',
            name='disruption_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='disruption',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
